<a href="Examples.hs3228420821463179852.out.html">prev</a></br><a href="failures.html">home</a></br><a href="Exception.hs750597385971307217.out.html">next</a></br></br><pre>5c5
< import qualified "MonadCatchIO-transformers" Control.Monad.CatchIO as M
---
> import qualified  Control.Monad.CatchIO as M
18a19
> 
</pre></br><h2>original</h2></br><pre>{-# LANGUAGE PackageImports #-}

module Propellor.Exception where

import qualified "MonadCatchIO-transformers" Control.Monad.CatchIO as M
import Control.Exception

import Propellor.Types
import Propellor.Message

-- | Catches IO exceptions and returns FailedChange.
catchPropellor :: Propellor Result -> Propellor Result
catchPropellor a = either err return =<< tryPropellor a
  where
    err e =  warningMessage (show e) >> return FailedChange

tryPropellor :: Propellor a -> Propellor (Either IOException a)
tryPropellor = M.try
</pre></br><h2>printed</h2></br><pre>{-# LANGUAGE PackageImports #-}

module Propellor.Exception where

import qualified  Control.Monad.CatchIO as M
import Control.Exception

import Propellor.Types
import Propellor.Message

-- | Catches IO exceptions and returns FailedChange.
catchPropellor :: Propellor Result -> Propellor Result
catchPropellor a = either err return =<< tryPropellor a
  where
    err e =  warningMessage (show e) >> return FailedChange

tryPropellor :: Propellor a -> Propellor (Either IOException a)
tryPropellor = M.try

</pre>